spring.application.name=train-booking-system

# MongoDB connection (edit as needed)
spring.data.mongodb.uri=mongodb://localhost:27017/trainbooking

server.port=0

# Nicer JSON dates
spring.jackson.serialization.write-dates-as-timestamps=false
# Basic auth credentials for Spring Security's default in-memory user
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN
